version: 0.0
os: linux
files:
  - source: /
    destination: /home/abdelali/devops/reactjs
hooks:
    AfterInstall:
       - location: scripts/copy-files.sh
         timeout: 300
         runas: root
    # ApplicationStart:
    #    - location: scripts/run-ansible-playbook.sh
    #      timeout: 300
    #      runas: abdelali

    
       
